# v2.0.0
name: Build Import App

inputs:
  githubToken:
    description: "GitHub Token"
    required: true

runs:
  using: composite

  steps:

    - name: Install dependencies for Import App
      shell: bash
      working-directory: src/VirtoCommerce.ImportModule.Web/import-app
      run: yarn

    - name: Build Import App
      shell: bash
      working-directory: src/VirtoCommerce.ImportModule.Web/import-app
      run: yarn build

